### ISSUE TITLE
Cannot find county name in savePreview.sh

### ISSUE THREAD

**Issue by astynax777** [dcsobral/seedGen#3]
The grep search:
`LINE=$(grep -m 1 "Generating county" log.txt)`
cannot match on the log line because the output is (e.g.) "Generating East Saiyu County" and not "Generating county".

**Comment by dcsobral** [comment]
That, `Generating XXX County`, is logged at the beginning of the world generation.  The one looked for in that line is displayed at the end:
```
2019-11-13T14:23:15 1266.048 INF WorldGenerator:Generating county 'South Pidiri County' took 21 minutes, 2 seconds
```
I prefer that one because it has convenient quotes I use to extract the county name.
